# Generated by Django 3.2.16 on 2023-05-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
