# Generated by Django 3.2.16 on 2023-06-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230524_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_in_chatroom',
            field=models.BooleanField(default=False),
        ),
    ]
