# Generated by Django 3.2.16 on 2023-06-20 12:00

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userHash',
            field=models.CharField(default=users.models.createRandomString, max_length=32, unique=True),
        ),
    ]
