# Generated by Django 3.2.16 on 2023-06-21 08:52

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_userhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_color',
            field=models.CharField(default=users.models.User.generate_random_color, max_length=7),
        ),
    ]
