# Generated by Django 3.2.16 on 2023-06-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_in_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ban_duration',
            field=models.IntegerField(default=0),
        ),
    ]
