version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  websocket:
    image: redis:5
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx-proxy-manager/data:/config
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - mynetwork

networks:
  mynetwork:
