version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    restart: unless-stopped

  websocket:
    image: redis:5
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    restart: unless-stopped

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - "80:80"
      - "8081:81"
      - "443:443"
    volumes:
      - ./nginx-proxy-manager/data:/config
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - mynetwork
    restart: unless-stopped

networks:
  mynetwork:

