# Generated by Django 3.2.16 on 2023-06-04 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import zone.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=zone.models.chatroom_img_upload_to)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('lifetime', models.IntegerField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('current_users', models.ManyToManyField(blank=True, related_name='current_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('max_slots', models.IntegerField(blank=True)),
                ('occupied_slots', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatroomMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('chatroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zone.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='chatroom_messages', to='zone.ChatroomMessages'),
        ),
    ]
