# Generated by Django 3.2.16 on 2023-05-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='location',
        ),
        migrations.AddField(
            model_name='zone',
            name='coordinates',
            field=models.JSONField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
