# Generated by Django 3.2.16 on 2023-05-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_auto_20230525_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
