# Generated by Django 3.2.16 on 2023-06-03 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import zone.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_comment_parent_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zone', '0003_alter_zone_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=zone.models.chatroom_img_upload_to)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('lifetime', models.IntegerField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('current_users', models.ManyToManyField(blank=True, related_name='current_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatroomMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.message')),
                ('chatroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zone.chatroom')),
            ],
            bases=('content.message',),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='messages', to='zone.ChatroomMessage'),
        ),
    ]
