# Generated by Django 3.2.16 on 2023-06-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0004_auto_20230603_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
