# Generated by Django 3.2.16 on 2023-05-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_privatemessage_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='message',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
