# Generated by Django 3.2.16 on 2023-06-03 07:33

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20230524_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=content.models.publications_img_upload_to),
        ),
    ]
